import { Logic } from "../logic.slint";
import { Theme } from "../theme.slint";
import { Store, SetupIndex } from "../store.slint";
import { SetupType } from "setup-type.slint";
import { SetPassword } from "set-passwrod.slint";
import { CreateAccount } from "create-account.slint";
import { RecoverAccount } from "recover-account.slint";

export component Setup inherits Rectangle {
    private property <SetupIndex> prev-index: SetupType;
    private property current-index <=> Store.current-setup-index;

    background: Theme.base-background;

    if current-index == SetupIndex.SetupType: SetupType {
        create-account => {
            current-index = SetupIndex.CreateAccount;
        }

        recover-account => {
            current-index = SetupIndex.RecoverAccount;
        }
    }

    if current-index == SetupIndex.CreateAccount: CreateAccount {
        back => {
            current-index = SetupIndex.SetupType;
        }

        confirm => {
            prev-index = SetupIndex.CreateAccount;
            Logic.save-mnemonics(self.mnemonics);
        }
    }

    if current-index == SetupIndex.RecoverAccount: RecoverAccount {
        back => {
            current-index = SetupIndex.SetupType;
        }

        confirm => {
            prev-index = SetupIndex.RecoverAccount;
            Logic.save-mnemonics(self.mnemonics);
        }
    }

    if current-index == SetupIndex.SetPassword: SetPassword {
        back => {
            current-index = prev-index;
        }

        confirm(username, password) => {
            Logic.save-username-info(username, password);
        }
    }
}
