import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { Theme, Icons } from "../theme.slint";
import { Mnemonic } from "../base/widgets.slint";

export component RecoverAccount inherits Rectangle {
    callback confirm <=> mic.confirm;
    callback back <=> mic.back;

    out property mnemonics <=> mic.mnemonics;

    mic := Mnemonic {
        is-show-btns: true;
        is-show-header: true;
        is-show-switch-mnemonic-counts-btn: true;
        header-title: Logic.tr(Store.is-cn, "恢复账户");

        init => {
            self.reset-mnemonics(12);
        }

        cancel => {
            self.back();
        }

        paste => {
            self.mnemonics = Logic.load-mnemonics();
        }
    }
}
