import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { Theme, Icons } from "../theme.slint";
import { ConfirmBtn } from "../base/widgets.slint";

export component SetupType inherits VerticalLayout {
    padding: Theme.padding * 5;
    spacing: Theme.spacing * 5;
    alignment: LayoutAlignment.center;

    callback create-account <=> create-btn.clicked;
    callback recover-account <=> recover-btn.clicked;

    create-btn := ConfirmBtn {
        icon: Icons.account;
        text: Logic.tr(Store.is-cn, "创建新账户");
    }

    recover-btn := ConfirmBtn {
        icon: Icons.recover;
        bg-color: Theme.danger-color.darker(20%);
        bg-pressed-color: self.bg-color.darker(30%);
        text: Logic.tr(Store.is-cn, "使用组记词恢复账户");
    }
}
