import { Theme, Icons } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Head, NoMessageImg } from "../../base/widgets.slint";

component TopHead inherits Head {
    icon: Icons.address;
    title: Logic.tr(Store.is-cn, "地址簿");
    hbox-alignment: LayoutAlignment.start;
}

component Body inherits Rectangle {
    NoMessageImg {
        width: root.width * 0.6;
        text: Logic.tr(Store.is-cn, "没有地址");
    }
}

export component AddressBook inherits VerticalLayout {
    head := TopHead { }
    body := Body { }
}
