import { Theme, Icons } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Divider, Head, ElevatedBtn, NoMessageImg, TransactionTile, TransactionTileEntry, TransactionTileStatus, SettingDetailInner, SlideCard } from "../../base/widgets.slint";

export global HistorySetting {
    in-out property <[TransactionTileEntry]> entries: [
        {
            uuid: "uuid-1",
            hash: "hash-1",
            balance: "$100.12",
            time: "2024-12-04 12:06:09",
            status: TransactionTileStatus.Success,
        },
        {
            uuid: "uuid-2",
            hash: "hash-1",
            balance: "$100.12",
            time: "2024-12-04 12:06:09",
            status: TransactionTileStatus.Pending,
        },
        {
            uuid: "uuid-3",
            hash: "hash-1",
            hash: "hash-1",
            balance: "$100.12",
            time: "2024-12-04 12:06:09",
            status: TransactionTileStatus.Error,
        },
        {
            uuid: "uuid-4",
            hash: "hash-1",
            hash: "hash-1",
            balance: "$100.12",
            time: "2024-12-04 12:06:09",
            status: TransactionTileStatus.Loading,
        }
    ];
}

component TopHead inherits Head {
    icon: Icons.history;
    title: Logic.tr(Store.is-cn, "历史记录");
    hbox-alignment: LayoutAlignment.start;
}

component TransactionTiles inherits SettingDetailInner {
    vbox-spacing: Theme.spacing * 2;
    for item[index] in HistorySetting.entries: Rectangle {
        private property <length> item-height: 80px;

        height: item-height;

        SlideCard {
            gap: Theme.padding * 2;

            icons: [
                {
                    icon: Icons.delete,
                    text: Logic.tr(Store.is-cn, "删除"),
                    colorize: Colors.red,
                },
            ];

            TransactionTile {
                height: item-height;
                entry: item;

                hash-clicked => {
                    Logic.open-tx-detail(item.network, item.hash);
                }

                icon-clicked => {
                    self.hash-clicked();
                }
            }

            icon-clicked => {
                Logic.remove-history(item.uuid);
            }
        }
    }
}

component Body inherits Rectangle {
    if HistorySetting.entries.length == 0: NoMessageImg {
        width: root.width * 0.6;
        text: Logic.tr(Store.is-cn, "没有记录");
    }

    if HistorySetting.entries.length > 0: TransactionTiles { }

    ElevatedBtn {
        x: root.width - self.width - Theme.padding * 4;
        y: root.height - self.height - Theme.padding * 4;

        icon: Icons.refresh;

        clicked => {
            Logic.refresh-all-pending-and-error-history();
        }
    }

}

export component History inherits VerticalLayout {
    head := TopHead { }
    body := Body { }
}
