import { Theme, Icons } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Head, ElevatedBtn, NoMessageImg, TransactionTile, TransactionTileEntry, TransactionTileStatus, SettingDetailInner, SlideCard } from "../../base/widgets.slint";

export global HistorySetting {
    in-out property <[TransactionTileEntry]> entries: [
        {
            hash: "hash-1",
            balance: "$100.12",
            time: "2024-12-04 12:06:09",
            status: TransactionTileStatus.Success,
        },
        {
            hash: "hash-1",
            balance: "$100.12",
            time: "2024-12-04 12:06:09",
            status: TransactionTileStatus.Pending,
        },
        {
            hash: "hash-1",
            balance: "$100.12",
            time: "2024-12-04 12:06:09",
            status: TransactionTileStatus.Error,
        }
    ];
}

component TopHead inherits Head {
    icon: Icons.history;
    title: Logic.tr(Store.is-cn, "历史记录");
    hbox-alignment: LayoutAlignment.start;
}

component TransactionTiles inherits Rectangle {
    SettingDetailInner {
        for item[index] in HistorySetting.entries: Rectangle {
            private property <length> item-height: 80px;

            height: item-height;

            SlideCard {
                gap: Theme.padding * 2;

                icons: [
                    {
                        icon: Icons.delete,
                        text: Logic.tr(Store.is-cn, "删除"),
                        colorize: Colors.red,
                    },
                ];

                TransactionTile {
                    height: item-height;
                    entry: item;

                    hash-clicked => {
                        // TODO
                        debug(item.hash);
                    }
                }

                icon-clicked => {
                    // TODO
                   debug("fwjfiweji");
                }
            }
        }
    }
}

component Body inherits Rectangle {
    if HistorySetting.entries.length == 0: NoMessageImg {
        width: root.width * 0.6;
        text: Logic.tr(Store.is-cn, "没有记录");
    }

    if HistorySetting.entries.length > 0: TransactionTiles { }
}

export component History inherits VerticalLayout {
    head := TopHead { }

    body := Body { }
}
