import { Theme, Icons } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Head, ElevatedBtn, NoMessageImg } from "../../base/widgets.slint";

component TopHead inherits Head {
    icon: Icons.history;
    title: Logic.tr(Store.is-cn, "历史记录");
    hbox-alignment: LayoutAlignment.start;
}

component Body inherits Rectangle {
    NoMessageImg {
        width: root.width * 0.6;
        text: Logic.tr(Store.is-cn, "没有记录");
    }

    // ElevatedBtn {
    //     x: root.width - self.width - Theme.padding * 4;
    //     y: root.height - self.height - Theme.padding * 4;
    //     icon: Icons.refresh;
    //     enable-rotation-animation: true;

    //     clicked => {
    //         Logic.fetch-all-find-entrys();
    //     }
    // }
}

export component History inherits VerticalLayout {
    head := TopHead { }
    body := Body { }
}
