import { Theme, Icons } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Head, Banner } from "../../base/widgets.slint";
import { TestModeBanner } from "test-mode-banner.slint";

component TopHead inherits Head {
    icon: Icons.crypto;
    icon-width: Theme.icon-size * 1.2;
    title: Logic.tr(Store.is-cn, "主页");
    hbox-alignment: LayoutAlignment.start;
}

component Body inherits Rectangle { }

export component Home inherits VerticalLayout {
    private property <string> network: Logic.get-current-network();

    head := TopHead { }

    if network != "main": TestModeBanner {
        network: root.network;
    }

    body := Body { }
}
