import { Theme, Icons } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Head } from "../../base/widgets.slint";

component TopHead inherits Head {
    icon: Icons.crypto;
    icon-width: Theme.icon-size * 1.2;
    title: Logic.tr(Store.is-cn, "主页");
    hbox-alignment: LayoutAlignment.start;
}

component Body inherits Rectangle {
    background: pink;
}

export component Home inherits VerticalLayout {
    head := TopHead { }
    body := Body { }
}
