import { Theme } from "../../theme.slint";
import { Store, TabIndex } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Util } from "../../util.slint";
import { Home } from "./home.slint";
import { Recipient } from "./recipient.slint";
import { History } from "./history.slint";
import { Setting } from "./setting.slint";

export component Bodyer inherits Rectangle {
    if TabIndex.Home == Store.current-tab-index : Home {}
    if TabIndex.Recipient == Store.current-tab-index : Recipient {}
    if TabIndex.History == Store.current-tab-index : History {}
    if TabIndex.Setting == Store.current-tab-index : Setting {}
}

