import { Theme, Icons } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Util } from "../../util.slint";
import { IconBtn, Head, Label, Link, CenterLayout, TokenRecipient } from "../../base/widgets.slint";
import { TestModeBanner } from "test-mode-banner.slint";


component TopHead inherits Head {
    icon: Icons.recipient;
    title: Logic.tr(Store.is-cn, "接收代币");
    hbox-alignment: LayoutAlignment.start;
}

component Body inherits TokenRecipient {
    is-show-header: false;
    account-name: Store.current-account.name;
    qrcode: Logic.qr-code(Store.current-account.pubkey);
    address: Store.current-account.pubkey;

    clicked-address => {
        Logic.open-account-detail(Logic.get-current-network(), Store.current-account.pubkey);
    }

    copy-address => {
        Logic.copy-to-clipboard(Store.current-account.pubkey);
    }
}

export component Recipient inherits VerticalLayout {
    private property <string> network: Logic.get-current-network();

    head := TopHead { }

    if network != "main": TestModeBanner {
        network: root.network;
    }

    body := Body { }
}
