import { Theme, Icons } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Util } from "../../util.slint";
import { IconBtn, Head, Label, Link, CenterLayout, SettingDetailInner } from "../../base/widgets.slint";
import { TestModeBanner } from "test-mode-banner.slint";


component TopHead inherits Head {
    icon: Icons.recipient;
    title: Logic.tr(Store.is-cn, "接收");
    hbox-alignment: LayoutAlignment.start;
}

component Body inherits SettingDetailInner {
    vbox-alignment: LayoutAlignment.center;
    vbox-spacing: Theme.spacing * 2;

    HorizontalLayout {
        alignment: LayoutAlignment.center;

        Label {
            font-size: Theme.title3-font-size;
            text: Store.current-account.name;
        }
    }

    HorizontalLayout {
        alignment: LayoutAlignment.center;

        Image {
            width: Math.min(300px, root.width * 0.8);
            height: self.width;
            source: Logic.qr-code(Store.current-account.pubkey);
        }
    }

    HorizontalLayout {
        spacing: Theme.spacing * 2;
        alignment: LayoutAlignment.center;

        Link {
            overflow: elide;
            horizontal-stretch: 1;
            wrap: TextWrap.no-wrap;
            text: Store.current-account.pubkey;
            font-size: Theme.default-font-size;
            color: self.has-hover ? Theme.link-text-color : Theme.primary-text-color;
            clicked => {
                Logic.open-account-detail(Logic.get-current-network(), Store.current-account.pubkey);
            }
        }

        IconBtn {
            icon: Icons.copy;
            clicked => {
                Logic.copy-to-clipboard(Store.current-account.pubkey);
            }
        }
    }
}

export component Recipient inherits VerticalLayout {
    private property <string> network: Logic.get-current-network();

    head := TopHead { }

    if network != "main": TestModeBanner {
        network: root.network;
    }

    body := Body { }
}
