import { LineEdit, CheckBox, ComboBox } from "std-widgets.slint";
import { Theme, Icons } from "../../theme.slint";
import { Logic } from "../../logic.slint";
import { Util } from "../../util.slint";
import { Store,  SettingUI, SettingDetailIndex, AccountEntry } from "../../store.slint";
import { LineInput, CenterLayout, OkCancelDialogSetting, Divider, Link, Brand, IconBtn, Label, Mnemonic, Head, SettingEntry, SettingDetail, SettingDetailInner, TabBtn, SettingDetailInnerVbox, SettingDetailLabel, TxtEdit, CancelBtn, ConfirmBtn, NoDataImg, Tag, RadioBtn, SlideCard, ListTile, IconsDialogSetting, ElevatedBtn, PasswordSetting, Avatar} from "../../base/widgets.slint";

export global AccountMnemonicSetting {
    in-out property <string> mnemonic;

    public function clear() {
        self.mnemonic = "";
    }
}

component UI inherits SettingDetail {
    title: Logic.tr(Store.is-cn, "界 面");

    public function get() -> SettingUI {
        font-size-lineedit.clear-focus();

        return {
            font-size: font-size-lineedit.text,
            font-family: fonts-combox.current-value,
            language: Store.setting-ui.language,
            is-dark: Store.setting-ui.is-dark,
        };
    }

    init => {
        font-size-lineedit.text = Store.setting-ui.font-size;
        fonts-combox.current-value = Store.setting-ui.font-family;
    }

    SettingDetailInner {
        SettingDetailInnerVbox {
            font-size-txt := SettingDetailLabel {
                text: Logic.tr(Store.is-cn, "字体大小");
            }

            font-size-lineedit := LineEdit {
                input-type: number;
                height: font-size-txt.preferred-height * 1.6;
                placeholder-text: Logic.tr(Store.is-cn, "10 ~ 50");
                text: Store.setting-ui.font-size;
            }
        }

        SettingDetailInnerVbox {
            fonts-label := SettingDetailLabel {
                text: Logic.tr(Store.is-cn, "字体样式");
            }

            fonts-combox := ComboBox {
                height: fonts-label.preferred-height * 1.6;
                model: ["Default", "Source Han Serif CN", "Plaster"];
                current-value: Store.setting-ui.font-family;
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr(Store.is-cn, "选择语言");
            }

            HorizontalLayout {
                HorizontalLayout {
                    width: 50%;
                    cn-radio := RadioBtn {
                        text: "中文";
                        checked: Store.setting-ui.language == "cn";
                        check => {
                            Store.setting-ui.language = "cn";
                        }
                    }
                }

                en-radio := RadioBtn {
                    text: "English";
                    checked: Store.setting-ui.language == "en";
                    check => {
                        Store.setting-ui.language = "en";
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr(Store.is-cn, "选择主题");
            }

            HorizontalLayout {
                HorizontalLayout {
                    width: 50%;
                    RadioBtn {
                        text: Logic.tr(Store.is-cn, "白天");
                        checked: !Theme.is-dark;
                        check => {
                            Theme.toggle();
                        }
                    }
                }

                RadioBtn {
                    text: Logic.tr(Store.is-cn, "黑暗");
                    checked: Theme.is-dark;
                    check => {
                        Theme.toggle();
                    }
                }
            }
        }
    }
}

component Accounts inherits Rectangle {
    callback back <=> sd.back;
    callback selected(int);

    sd := SettingDetail {
        title: Logic.tr(Store.is-cn, "账户管理");

        private property <length> item-height: 80px;

        SettingDetailInner {
            for item[index] in Store.accounts: VerticalLayout {
                alignment: LayoutAlignment.center;

                ListTile {
                    private property <int> icon-index: Util.bound(0, item.avatar-index, IconsDialogSetting.icons.length - 1);
                    private property <bool> is-current-account: item.uuid == Store.current-account.uuid;

                    height: item-height;
                    background: self.has-hover ? Theme.base-background.darker(3%) : Theme.base-background;
                    border-color: Theme.invert-base-color;
                    border-width: is-current-account ? 1px : 0px;
                    border-radius: Theme.border-radius;
                    drop-shadow-blur: Theme.padding * 2;
                    drop-shadow-color: Theme.base-background-drop-shadow;

                    is-show-left-icon: true;
                    left-icon: IconsDialogSetting.icons[icon-index];
                    left-icon-is-avatar: true;
                    left-icon-size: item-height * 2 / 5;
                    left-icon-colorize: Theme.icon-color;
                    left-icon-border-width: 2px;
                    left-icon-background: Theme.secondary-background;
                    left-icon-hover-background: self.left-icon-background.darker(5%);

                    title-text: item.name;
                    subtitle-text: "$" + item.balance;
                    middle-mouse-cursor: MouseCursor.pointer;

                    is-show-right-icon: true;
                    right-icon: Icons.switch;

                    left-clicked => {
                        IconsDialogSetting.set(true, "account", item.uuid);
                    }

                    middle-clicked => {
                        root.selected(index);
                    }

                    right-clicked => {
                        Logic.switch-account(Store.current-account.uuid, item.uuid);
                    }
                }
            }
        }
    }

    ElevatedBtn {
        x: root.width - self.width - Theme.padding * 4;
        y: root.height - self.height - Theme.padding * 4;
        icon: Icons.add-small;

        clicked => {
            PasswordSetting.set(true, "new-account", "");
        }
    }
}

component AccountDetail inherits SettingDetail {
    in property <int> selected-account-index;

    private property <AccountEntry> selected-account: Store.accounts[selected-account-index];
    private property <int> icon-index: Util.bound(0, selected-account.avatar-index, IconsDialogSetting.icons.length - 1);

    title: Logic.tr(Store.is-cn, "账 户");

    SettingDetailInner {
        Rectangle {
            height: Math.max(root.height * 0.2, 200px);
            background: Theme.secondary-background;
            border-radius: Theme.border-radius;

            Avatar {
                height: 50%;
                width: self.height;
                background: Theme.third-brand-color;
                icon: IconsDialogSetting.icons[icon-index];

                clicked => {
                    IconsDialogSetting.set(true, "account", selected-account.uuid);
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr(Store.is-cn, "账户名称");
            }

            LineInput {
                enabled: false;
                width: root.width - Theme.padding * 4;
                text: selected-account.name;
                icon: self.enabled ? Icons.checked-box : Icons.edit;
                clicked => {
                    self.enabled = !self.enabled;

                    if (self.enabled) {
                        self.focus();
                    } else {
                        Logic.update-account-name(selected-account.uuid, self.text);
                    }
                }

                accepted => {
                    self.clear-focus();
                    self.enabled = !self.enabled;
                    Logic.update-account-name(selected-account.uuid, self.text);
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr(Store.is-cn, "账户地址");
            }

            LineInput {
                enabled: false;
                width: root.width - Theme.padding * 4;
                text: selected-account.pubkey;
                icon: Icons.copy;
                clicked => {
                    Logic.copy-to-clipboard(self.text);
                }
            }
        }

        SettingEntry {
            text: Logic.tr(Store.is-cn, "显示组记词");
            icon: Icons.mnemonic;
            clicked => {
                PasswordSetting.set(true, "show-mnemonic", "");
            }
        }

        VerticalLayout {
            padding-top: Theme.padding * 5;
            CancelBtn {
                icon: Icons.delete;
                colorize: Theme.danger-color;
                text-color: Theme.danger-color;
                border-radius: Theme.border-radius;
                font-size: Theme.title3-font-size;
                text: Logic.tr(Store.is-cn, "移除账户");

                clicked => {
                    OkCancelDialogSetting.set(true, "warning", Logic.tr(Store.is-cn, "警告"), Logic.tr(Store.is-cn, "是否删除账户？"), "remove-account", selected-account.uuid);
                }
            }
        }
    }
}

component AccountMnemonic inherits SettingDetailInner {
    callback back();

    mc := Mnemonic {
        is-read-only: true;
        is-show-header: true;
        header-title: Logic.tr(Store.is-cn, "组记词");
        mnemonics: Logic.split-mnemonic(AccountMnemonicSetting.mnemonic);

        copy => {
            Logic.copy-to-clipboard(Logic.join-mnemonics(self.mnemonics));
        }

        back => {
            AccountMnemonicSetting.clear();
            root.back();
        }
    }
}

component About inherits SettingDetail {
    title: Logic.tr(Store.is-cn, "关 于");

    VerticalLayout {
        alignment: start;
        spacing: Theme.spacing * 4;
        padding: Theme.padding * 2;
        padding-top: Theme.padding * 4;

        HorizontalLayout {
            alignment: center;

            Label {
                color: Theme.brand-color;
                text: Store.about-dialog.title;
                font-size: Theme.title1-font-size;
            }
        }

        Label {
            horizontal-alignment: center;
            text: Store.about-dialog.text;
            wrap: word-wrap;
        }

        VerticalLayout {
            spacing: Theme.spacing * 2;
            HorizontalLayout {
                alignment: center;
                spacing: Theme.spacing * 2;

                Label {
                    text: "🎉❤Buy Me a Coffee(MetaMask)❤🎉";
                }

                IconBtn {
                    icon: Icons.copy;
                    clicked => {
                        Logic.copy-to-clipboard(Store.about-dialog.sponsor);
                    }
                }
            }

            HorizontalLayout {
                alignment: center;
                Link {
                    wrap: word-wrap;
                    text: Store.about-dialog.sponsor;
                    color: Theme.placeholder-text-color;
                    font-size: Theme.default-font-size - 2px;

                    clicked => {
                        // Util.open-url("https://etherscan.io/address/" + Store.about-dialog.sponsor);
                    }
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            Brand {
                width: 35%;
            }
        }
    }
}

component Help inherits SettingDetail {
    title: Logic.tr(Store.is-cn, "帮 助");

    Flickable {
        SettingDetailInner {
            Label {
                text: Store.is-cn ? Store.help-dialog.text-cn : Store.help-dialog.text-en;
                wrap: word-wrap;
            }
        }
    }
}

component Donate inherits SettingDetail {
    title: Logic.tr(Store.is-cn, "捐 赠");

    private property <bool> is-wechat: true;

    SettingDetailInner {
        vbox-alignment: LayoutAlignment.stretch;

        HorizontalLayout {
            TabBtn {
                width: 50%;
                height: Theme.footer-height;
                icon: Icons.wechat-light;
                text: Logic.tr(Store.is-cn, "微信支付");
                checked: root.is-wechat;
                clicked => {
                    root.is-wechat = true;
                }
            }

            TabBtn {
                height: Theme.footer-height;
                icon: Icons.metamask-light;
                text: Logic.tr(Store.is-cn, "小狐狸（加密）支付");
                checked: !root.is-wechat;
                clicked => {
                    root.is-wechat = false;
                }
            }
        }

        Rectangle {
            if root.is-wechat: Image {
                source: Icons.wechat-pay;
                width: Math.min(root.width * 0.8, root.height * 0.8);
                height: self.width;
            }

            if !root.is-wechat: Image {
                source: Icons.metamask-pay;
                width: Math.min(root.width * 0.6, root.height * 0.6);
                height: self.width;
            }
        }
    }
}

component Body inherits VerticalLayout {
    alignment: start;
    spacing: Theme.spacing;

    in-out property current-setting-detail-index <=> Store.current-setting-detail-index;

    callback switch(SettingDetailIndex);

    head := Head {
        hbox-alignment: LayoutAlignment.start;
        icon: Icons.setting-fill;
        title: Logic.tr(Store.is-cn, "设置");
    }

    Flickable {
        viewport-height: vbox.preferred-height;

        vbox := VerticalLayout {
            spacing: Theme.spacing * 2;

            SettingEntry {
                text: Logic.tr(Store.is-cn, "界 面");
                icon: Icons.ui;

                clicked => {
                    root.current-setting-detail-index = SettingDetailIndex.UI;
                    root.switch(SettingDetailIndex.UI);
                }
            }

            SettingEntry {
                text: Logic.tr(Store.is-cn, "账 户");
                icon: Icons.ui;

                clicked => {
                    root.current-setting-detail-index = SettingDetailIndex.Accounts;
                    root.switch(SettingDetailIndex.Accounts);
                }
            }

            SettingEntry {
                text: Logic.tr(Store.is-cn, "关 于");
                icon: Icons.about-light;
                clicked => {
                    root.current-setting-detail-index = SettingDetailIndex.About;
                }
            }

            SettingEntry {
                text: Logic.tr(Store.is-cn, "帮 助");
                icon: Icons.help-light;
                clicked => {
                    root.current-setting-detail-index = SettingDetailIndex.Help;
                }
            }

            SettingEntry {
                text: Logic.tr(Store.is-cn, "捐 赠");
                icon: Icons.donate;
                clicked => {
                    root.current-setting-detail-index = SettingDetailIndex.Donate;
                }
            }

            SettingEntry {
                text: Logic.tr(Store.is-cn, "Github");
                icon: Icons.github;
                clicked => {
                    Util.open-url("Default","https://github.com/Heng30/solana-wallet-sollet");
                }
            }
        }
    }
}

export component Setting inherits Rectangle {
    private property <int> selected-account-index;

    if Store.current-setting-detail-index == SettingDetailIndex.Home: Body { }

    if Store.current-setting-detail-index != SettingDetailIndex.Home: Rectangle {
        if Store.current-setting-detail-index == SettingDetailIndex.UI: UI {
            back => {
                if (self.get().font-size == "") {
                    Logic.show-message(Logic.tr(Store.is-cn, "非法输入，输入不能为空"), "warning");
                    return;
                }
                Store.current-setting-detail-index = SettingDetailIndex.Home;
                Logic.set-setting-ui(self.get());
            }
        }

        if Store.current-setting-detail-index == SettingDetailIndex.Accounts: Accounts {
            back => {
                Store.current-setting-detail-index = SettingDetailIndex.Home;
            }

            selected(account-index) => {
                root.selected-account-index = account-index;
                Store.current-setting-detail-index = SettingDetailIndex.AccountDetail;
            }
        }

        if Store.current-setting-detail-index == SettingDetailIndex.AccountDetail: AccountDetail {
            selected-account-index: root.selected-account-index;

            back => {
                Store.current-setting-detail-index = SettingDetailIndex.Accounts;
            }
        }

        if Store.current-setting-detail-index == SettingDetailIndex.AccountMnemonic: AccountMnemonic {
            back => {
                Store.current-setting-detail-index = SettingDetailIndex.AccountDetail;
            }
        }

        if Store.current-setting-detail-index == SettingDetailIndex.About: About {
            back => {
                Store.current-setting-detail-index = SettingDetailIndex.Home;
            }
        }

        if Store.current-setting-detail-index == SettingDetailIndex.Help: Help {
            back => {
                Store.current-setting-detail-index = SettingDetailIndex.Home;
            }
        }

        if Store.current-setting-detail-index == SettingDetailIndex.Donate: Donate {
            back => {
                Store.current-setting-detail-index = SettingDetailIndex.Home;
            }
        }
    }
}
