import { Theme, Icons } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Util } from "../../util.slint";
import { OkCancelDialogSetting, IconBtn, Head, Label, Tag, Link, NoDataImg, NoMessageImg, CenterLayout } from "../../base/widgets.slint";
import { Theme } from "../../theme.slint";

component TopHead inherits Head {
    icon: Icons.recipient;
    title: Logic.tr(Store.is-cn, "接收");
    hbox-alignment: LayoutAlignment.start;
}

component Body inherits Rectangle {
    background: yellow;
}

export component Recipient inherits VerticalLayout {
    head := TopHead { }
    body := Body { }
}
