import { Theme } from "../theme.slint";
import { TokenTile, TokenTileWithSwitch, TokenTileEntry, TokenTileWithSwitchEntry } from "token-tile.slint";
import { SettingDetailInner } from "setting-detail.slint";

export component TokenList inherits SettingDetailInner {
    in-out property <[TokenTileEntry]> entries;

    vbox-alignment: LayoutAlignment.start;
    vbox-spacing: Theme.spacing * 2;

    callback clicked(TokenTileEntry);

    for item[index] in entries: TokenTile {
        entry: item;

        clicked => {
            root.clicked(item);
        }
    }
}

export component TokenListWithSwitch inherits SettingDetailInner {
    in-out property <[TokenTileWithSwitchEntry]> entries;

    vbox-alignment: LayoutAlignment.start;
    vbox-spacing: Theme.spacing * 2;

    callback clicked(TokenTileEntry);
    callback toggled(bool, TokenTileEntry);

    for item[index] in entries: TokenTileWithSwitch {
        entry: item.entry;
        checked: item.checked;

        clicked => {
            root.clicked(item.entry);
        }

        toggled => {
            root.toggled(self.checked, item.entry);
        }
    }
}
