import { Theme, Icons } from "./theme.slint";
import { Logic } from "./logic.slint";
import { Store, SettingDetailIndex, SettingDeveloperMode, SettingSecurityPrivacy, SendTokenProps, HomeIndex } from "./store.slint";
import { Util } from "./util.slint";
import { Panel } from "./panel/panel.slint";
import { LoadingStatus, Toast, IconsDialogSetting, IconsDialog, OkCancelDialogV2, Blanket, LanguageDialog, OkCancelDialogSetting, LandingPage, Password, PasswordSetting, Password, AddressBookEntry, AddressBookSetting, AboutSetting, TransactionTileEntry, TransactionTileStatus, TokenTileEntry, TokenTileWithSwitchEntry } from "./base/widgets.slint";
import { Setup } from "./setup/panel.slint";
import { CreateAccount } from "./setup/create-account.slint";
import { AccountMnemonicSetting } from "./panel/bodyer/setting.slint";
import { HistorySetting } from "./panel/bodyer/history.slint";
import { TokensSetting } from "./panel/bodyer/home.slint";

export component AppWindow inherits Window {
    default-font-size: Theme.default-font-size;
    default-font-family: Theme.default-font-family;
    preferred-width: Theme.default-width;
    preferred-height: Theme.default-height;

    background: Theme.base-background;
    icon: Icons.brand;
    title: "sollaw";

    public function show-login-page() {
        if (!Store.is-first-run && !Store.is-show-setup-page && !Store.is-show-landing-page) {
            Store.is-login = true;
            PasswordSetting.set(true, "login", "");
        }
    }

    if !Store.is-show-setup-page: Panel { }
    if Store.is-show-setup-page: Setup { }

    if IconsDialogSetting.show || PasswordSetting.show || OkCancelDialogSetting.show: Blanket {
        clicked => {
            IconsDialogSetting.show = false;
            PasswordSetting.show = false;
            OkCancelDialogSetting.show = false;
        }
    }

    if IconsDialogSetting.show: IconsDialog {
        is-prevent-event-forward: true;
        select-index(handle-type, index, user-data) => {
            if (handle-type == "account") {
                Logic.update-account-avatar-index(user-data, index);
            }
        }
    }

    if PasswordSetting.show: Password {
        private property <string> err;
        is-show-header: !Store.is-login;

        init => {
            self.focus();
        }

        back => {
            PasswordSetting.show = false;
        }

        cancel => {
            if (Store.is-login) {
                Logic.show-message(Logic.tr(Store.is-cn, "请输入密码"), "info");
            } else {
                PasswordSetting.show = false;
            }
        }

        confirm(handle-type, password, user-data) => {
            self.err = Logic.is-valid-password(password);

            if (self.err != "") {
                return self.err;
            }
            if (handle-type == "new-account") {
                Logic.new-account("", password);
            } else if (handle-type == "show-mnemonic") {
                Logic.show-mnemonic(password);
            } else if (handle-type == "remove-account") {
                Logic.remove_account(password, user_data);
            } else if (handle-type == "remove-all-accounts") {
                Logic.remove-all-accounts(password);
            } else if (handle-type == "evaluate-transaction-fee") {
                Logic.evaluate-transaction-fee(password, TokensSetting.sender.props);
            } else if (handle-type == "login") {
                Logic.login(password);
                return "";
            }
            PasswordSetting.show = false;
            return "";
        }
    }

    if OkCancelDialogSetting.show: OkCancelDialogV2 {
        is-prevent-event-forward: true;
        width: Math.min(root.width * 0.9, 380px);
    }

    if Store.message.text != "": Toast {
        x: root.width / 2 - self.width / 2;
        y: 50px;
        inner-max-width: root.width * 80%;
        text: Store.message.text;
        type: Store.message.text-type;
        clicked => {
            Logic.copy-to-clipboard(self.text);
        }
    }

    if Store.is-show-landing-page: LandingPage {
        details: [
            {
                picture: Icons.landing-account,
                description: Logic.tr(Store.is-cn, "创建账户和使用组记词恢复账户"),
            },
            {
                picture: Icons.landing-send,
                description: Logic.tr(Store.is-cn, "查看、发送和接收Sol代币和Solana的通证"),
            },
            {
                picture: Icons.landing-welcome,
                description: Logic.tr(Store.is-cn, "欢迎使用，享受你的加密之旅"),
            }
        ];
        skipped => {
            Store.is-show-landing-page = false;
        }
    }
}

export { Util, Logic, Store, Theme, Icons, IconsDialogSetting, LoadingStatus, SettingDetailIndex, AccountMnemonicSetting, AddressBookEntry, AddressBookSetting, PasswordSetting, AboutSetting, TransactionTileEntry, TransactionTileStatus, HistorySetting, SettingDeveloperMode, TokenTileEntry, TokensSetting, TokenTileWithSwitchEntry, SendTokenProps, HomeIndex, SettingSecurityPrivacy }
