export enum TabIndex {
    Home,
    Recipient,
    History,
    AddressBook,
    Setting,
    None,
}

export enum SettingDetailIndex {
    Home,
    UI,
    About,
    Help,
    Donate,
}

export enum SetupIndex {
    SetupType,
    CreateAccount,
    RecoverAccount,
    SetPassword,
}

export struct AccountEntry {
    uuid: string,
    name: string,
    pubkey: string,
    derive-index: int,
}

export struct MessageItem {
    text: string,
    text-type: string,
}

export struct SettingUI {
    font-size: string,
    font-family: string,
    language: string,
    is-dark: bool,
}

export struct AboutDialog {
    show: bool,
    title: string,
    text: string,
    sponsor: string,
}

export global Store {
    in-out property <SetupIndex> current-setup-index: SetupIndex.SetupType;
    in-out property <TabIndex> current-tab-index: TabIndex.Home;
    private property <TabIndex> current-tab-index-tmp: TabIndex.None;
    in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.Home;

    in-out property <AccountEntry> current-account;
    in-out property <[AccountEntry]> accounts: [];

    in-out property <MessageItem> message;
    in-out property <bool> is-first-run;
    in-out property <bool> is-show-landing-page;
    in-out property <bool> is-show-setup-page: false;
    in-out property <bool> is-cn: setting-ui.language == "cn";
    in-out property <SettingUI> setting-ui: {
        font-size: "16",
        font-family: "Source Han Serif CN",
        language: "cn",
        is-dark: false,
    };

    in-out property <AboutDialog> about-dialog: {
        show: false,
        title: "sollet v0.0.1",
        text: "Based on Slint-UI. Copyright 2022-2030. All rights reserved. The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.",
        sponsor: "0xf1199999751b1a3A74590adBf95401D19AB30014",
    };

    in-out property <{show: bool, text-cn: string, text-en: string}> help-dialog: {
        show: false,
        text-cn:
          "- 点击[订阅]选项卡右上角的列表图标打开RSS列表。\n\n" + "- 向右滑动[订阅]和[收藏夹]的条目，可收藏或删除条目。\n\n" + "- 设置后，点击左上角的返回按钮。对设置进行保存。\n\n" + "- 曾经下载过的文章会缓存起来，避免文章重复显示。进入到[设置]选项卡可清除缓存。\n\n" + "- 将语言切换为英文后，在[发现]页面刷新可获取英文RSS。",
        text-en:
          "- Click the top-right list icon of the [RSS] selected card to open the RSS list.\n\n" + "- Swipe right on the [RSS] and [Collection] items to collect or delete items.\n\n" + "- After setting, click the back button in the upper left corner. Save the settings.\n\n" + "- In case of don't show the same articles, It will cache the articles after syncing. You can enter the [Setting] selected card to clear cache.\n\n",
    };

    public function switch-tab(tab-index: TabIndex) {
        current-tab-index = tab-index;
    }

    public function refresh-current-tab() {
        current-tab-index-tmp = current-tab-index;
        current-tab-index = TabIndex.None;
        current-tab-index = current-tab-index-tmp;
    }
}
