export enum TabIndex {
    Home,
    Recipient,
    History,
    Setting,
    None,
}

export enum SettingDetailIndex {
    Home,
    UI,
    About,
    Help,
    Donate,

    Accounts,
    AccountDetail,
    AccountMnemonic,
    SecurityAndPrivacy,
    ResetPassword,
    DeveloperMode,
    AddressBook,
    AddressBookDetail,
}

export enum SetupIndex {
    SetupType,
    CreateAccount,
    RecoverAccount,
    SetPassword,
}

export enum HomeIndex {
    Home,
    Send,
    Management,
}

export struct AccountEntry {
    uuid: string,
    name: string,
    pubkey: string,
    derive-index: int,
    avatar-index: int,
    balance: string,
}

export struct MessageItem {
    text: string,
    text-type: string,
}

export struct SettingUI {
    font-size: string,
    font-family: string,
    language: string,
    is-dark: bool,
}

export struct SettingDeveloperMode {
    enabled: bool,
    network: string,
}

export global Store {
    in-out property <HomeIndex> current-home-index: HomeIndex.Home;
    in-out property <SetupIndex> current-setup-index: SetupIndex.SetupType;
    in-out property <TabIndex> current-tab-index: TabIndex.Home;
    private property <TabIndex> current-tab-index-tmp: TabIndex.None;
    in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.Home;

    in-out property <AccountEntry> current-account: {
        uuid: "uuid-1",
        name: "Account-1",
        pubkey: "pubkey-test",
        derive-index: 0,
        avatar-index: 0,
        balance: "$100.21",
    };

    in-out property <[AccountEntry]> accounts: [
        {
            uuid: "uuid-1",
            name: "Account-1",
            pubkey: "pubkey-test",
            derive-index: 0,
            avatar-index: 0,
            balance: "$100.21",
        }
    ];

    in-out property <MessageItem> message;
    in-out property <bool> is-first-run;
    in-out property <bool> is-show-landing-page;
    in-out property <bool> is-show-setup-page;
    in-out property <bool> is-cn: setting-ui.language == "cn";
    in-out property <SettingUI> setting-ui: {
        font-size: "16",
        font-family: "Source Han Serif CN",
        language: "cn",
        is-dark: false,
    };

    in-out property <[string]> helps: is-cn ? [
        "点击[订阅]选项卡右上角的列表图标打开RSS列表。",
        "向右滑动[订阅]和[收藏夹]的条目，可收藏或删除条目。",
        "设置后，点击左上角的返回按钮。对设置进行保存。",
    ] : [
        "Click the top-right list icon of the [RSS] selected card to open the RSS list.",
        "Swipe right on the [RSS] and [Collection] items to collect or delete items.",
        "After setting, click the back button in the upper left corner. Save the settings."
    ];

    public function switch-tab(tab-index: TabIndex) {
        current-tab-index = tab-index;
    }

    public function refresh-current-tab() {
        current-tab-index-tmp = current-tab-index;
        current-tab-index = TabIndex.None;
        current-tab-index = current-tab-index-tmp;
    }
}
