import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { Theme, Icons } from "../theme.slint";
import { ConfirmBtn } from "../base/widgets.slint";

export component SetupType inherits VerticalLayout {
    padding: Theme.padding * 5;
    spacing: Theme.spacing * 5;
    alignment: LayoutAlignment.center;

    callback create-account <=> create-btn.clicked;
    callback recover-account <=> recover-btn.clicked;

    create-btn := ConfirmBtn {
        icon: Icons.account;
        border-radius: Theme.border-radius;
        font-size: Theme.title3-font-size;
        text: Logic.tr(Store.is-cn, "创建账户");
    }

    recover-btn := ConfirmBtn {
        icon: Icons.recover;
        border-radius: Theme.border-radius;
        bg-color: Theme.info-color;
        bg-pressed-color: self.bg-color.darker(30%);
        font-size: Theme.title3-font-size;
        text: Logic.tr(Store.is-cn, "恢复账户");
    }
}
